Update null-object-pattern.md
ardalis/DevIQ-gatsby pull request #102
Opened 2022-04-29 07:44 UTC by zzfima

Add NullObjectCustomer
Remove some typo "c =&gt;"

2022-04-29 13:50 UTC, ardalis commented on src/docs/design-patterns/null-object-pattern.md
> +Another way implement the Null Object Pattern, is by using inhetance:
```suggestion
Another way implement the Null Object Pattern, is by using inheritance:
```

2022-04-29 13:51 UTC, ardalis commented on src/docs/design-patterns/null-object-pattern.md
> +                .List(c.PhoneNumber == phoneNumber)
```suggestion
                .List(c => c.PhoneNumber == phoneNumber)
```
The previous syntax was correct. It's a lambda expression in C#.

2022-04-29 13:52 UTC, ardalis commented on src/docs/design-patterns/null-object-pattern.md
> +If using NullObjectCustomer, code is very same, except of:
```suggestion
If using `NullObjectCustomer`, code is the same, except for:
```

2022-04-29 13:52 UTC, ardalis requested changes
minor changes please

2022-04-29 21:13 UTC, ardalis commented
You don't want to add the java class you showed?

2022-04-30 06:56 UTC, zzfima commented
@ardalis i closed it y mistake

2022-05-02 10:28 UTC, zzfima commented
i have accept 1 suggestion

2022-05-06 06:18 UTC, zzfima commented
@ardalis hi I new in GitHub open source. Shall I do something?

2022-05-10 13:49 UTC, merged

2022-05-10 13:49 UTC, ardalis commented
Sorry; got busy. :) 

Thanks!